### ISSUE TITLE
Non-existent service

### ISSUE THREAD

**Issue by raupie** [netgen/ezpublish-community-sylius#1]
I tried going through the installation procedure but I am getting a 503 Service Unavailable error when trying to view the site as well as a "You have requested a non-existent service "fos_user.doctrine_registry" when trying to clear the cache.

**Comment by emodric** [comment]
Hi,

this is probably due to the fact that Sylius 0.14 depends on `"friendsofsymfony/user-bundle": "2.0.*@dev"`, aka master branch, which probably introduced breaking changes somewhere along the line.

I'm not sure anything can be done with this unfortunatelly.

This repo is basically deprecated and not maintained any more, as it uses relativelly old eZ version (2014.11) and Sylius (0.14). We're currently working on connecting eZ Platform and Sylius (currently on 0.15). We're also waiting for Sylius to have a stable release so we can bring the integration up to date with stable releases.
